### ISSUE TITLE
Doesn't play well with redis-namespace

### ISSUE THREAD

**Issue by blarralde** [mhenrixon/sidekiq-unique-jobs#196]
I couldn't quite figure out where it happens in the code, but somehow namespaces are not added to the main hash key. Example of what I see in redis:

```
redis = Redis::Namespace.new("sidekiq", redis: REDIS)
redis.keys
=> ["sidekiq:processes", "sidekiq:stat:failed", "sidekiq:sidekiq:status:b635df490af7a6fc0441892f", "uniquejobs", "sidekiq:uniquejobs:4a3b0ea5cd32400c837ec73565aa178d"]
redis.hgetall "uniquejobs"
=> {"ac11feaaea4378ba6f1f7df0"=>"sidekiq:uniquejobs:4a3b0ea5cd32400c837ec73565aa178d"}
redis.get "sidekiq:uniquejobs:4a3b0ea5cd32400c837ec73565aa178d"
=> "ac11feaaea4378ba6f1f7df0"
```

So somehow the hash doesn't get namespaced, but the unique job key inside of it does.

My guess would be that:
- the unique job key digest somehow receives the namespace in https://github.com/mhenrixon/sidekiq-unique-jobs/blob/11f88a3c5d5f7058d988f9ffd7854b1dfd2cea04/lib/sidekiq_unique_jobs/unique_args.rb
- the redis connection the gem is using isn't quite Sidekiq's

**Comment by dpetersen** [comment]
I don't know a lot about this gem, but I'm trying to sort out a problem with an app that uses it and I was trying to figure out if it was namespace safe. It appears not. As far as an explanation, I haven't had time to test this out, but the gem uses [Lua scripts](https://github.com/mhenrixon/sidekiq-unique-jobs/tree/11f88a3c5d5f7058d988f9ffd7854b1dfd2cea04/redis) that are evaluated and run on your redis server. I'm guessing that it circumvents the way redis-namespace works. I *think* you can configure a `unique_prefix` ([as seen here](https://github.com/mhenrixon/sidekiq-unique-jobs/blob/11f88a3c5d5f7058d988f9ffd7854b1dfd2cea04/lib/sidekiq-unique-jobs.rb#L25) and [used here](https://github.com/mhenrixon/sidekiq-unique-jobs/blob/11f88a3c5d5f7058d988f9ffd7854b1dfd2cea04/lib/sidekiq_unique_jobs/lock/until_executed.rb#L44-L46)), but it still doesn't appear to namespace the key, it just adds something to the way jobs get hashed so that different apps that work on a shared redis won't collide.

**Comment by mhenrixon** [comment]
Support for namespace has been dropped.

**Comment by aCandidMind** [comment]
Wouldn't it make sense to drop that code then?
https://github.com/mhenrixon/sidekiq-unique-jobs/search?q=namespace

**Comment by mhenrixon** [comment]
👍 @aCandidMind

**Comment by mengqing** [comment]
Any reason why support for namespace has been dropped? We run our sidekiq server on a namespace and currently this doesn't work (eg: when specifying replace when on conflict, the existing job doesn't get replaced)

**Comment by mhenrixon** [comment]
Partly because doing so means supporting a bad way of doing the Redis thing, partly because I am lazy.

- http://www.mikeperham.com/2015/09/24/storing-data-with-redis/
