### ISSUE TITLE
unique_args method suppresses all `NameError` exceptions

### ISSUE THREAD

**Issue by percyhanna** [mhenrixon/sidekiq-unique-jobs#219]
We recently discovered that we had workers raising `NoMethodError` exceptions because we weren't properly handling/validating input parameters. However, these errors were [unknowingly being silenced](https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/lib/sidekiq_unique_jobs/unique_args.rb#L65-L68), and would simply continue on as if nothing bad had happened at all.

Rescuing all `NameError` exceptions is overly aggressive. My assumption is that the `rescue` block can be removed entirely? It seems there are already guards agains the method being undefined.

**Comment by mhenrixon** [comment]
I agree that hiding the issue is really bad. There should definitely be some logging there, the problem is that in some situations the worker class can't be instantiated because it isn't part of the codebase where we are pushing from. It might only be part of the server. This means that it was crashing for those same people when the client was checking for uniqueness. 

I can't really have the unique jobs crash here. Would sufficient log output be sufficient for your situation? I could potentially add a configuration option for raising all errors as some specific gem exception and let you deal with it that way. Turning of catching the name error will cause problem for other people. 

Alternatively maybe it makes sense to catch the NoMethodError and re raise it. I didn't know NoMethodError was a kind of NameError. Thought NameError's where only for when a class couldn't be found. 

Learning new things every day.

**Comment by percyhanna** [comment]
For one, the `rescue` doesn't even seem to be in the right place. Aside from that, [this code](https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/lib/sidekiq_unique_jobs/unique_args.rb#L123-L128) implies to me that the error would never raise anyway. I'm not sure exactly under what situation the error(s) that were being experienced were happening, but the main problem is that the `rescue` is too broad. If `@worker_class` is a `String` because [the constant is not defined](https://github.com/mhenrixon/sidekiq-unique-jobs/blob/c4385a406cc730cef81b911699cf23aa3b225b9f/lib/sidekiq-unique-jobs.rb#L59-L64), then it likely won't respond to `unique_args_method`, so I'm not sure what the problem is?

Is there a test case written for this specific situation? I wonder if it still needs the `rescue` inside `unique_args`, since there's also a `rescue NameError` in `worker_class_constantize`.
