### ISSUE TITLE
sidekiq-unique-job with ActiveJob

### ISSUE THREAD

**Issue by Etienne-C** [mhenrixon/sidekiq-unique-jobs#238]
Hi,

I am trying to use sidekiq-unique-job with ActiveJob

The Job has to create new matching score if the user_id is not existing in the Matching model 
or update the matching score  if the matching already exist.
The job during about 3 minutes to run.

The problem is if during the job run, the user update his profile a new job is sending and I have duplicated matchings.

I tried to use sidekiq-unique-job with ":until_and_while_executing" but that seems not working. 

```ruby
 Sidekiq.default_worker_options = {
   unique: :until_and_while_executing,
   unique_args: ->(args) { [ args.first.except('user_id') ] }
 } 

 class SetMatchingsUserJob < ApplicationJob
    queue_as :default
    def perform(user_id) 
      user = User.find(user_id)
        (...)
      end
   end
 end
````

**Comment by mhenrixon** [comment]
Unfortunately the choice of using ActiveJob prevents you from using some of the most interesting features of `Sidekiq` (like proper unique jobs). I strongly recommend you use sidekiq directly instead.

I seriously consider not supporting ActiveJob due to all these questions. Where I work currently we are switching from ActiveJob to pure Sidekiq because it takes a bunch of abstractions and such on ActiveJob to make it work right with any semi-complex requirements.

Seems like you are also running into some such. Any chance of switching over to just using Sidekiq directly?

**Comment by MFRWDesign** [comment]
I think this deserves a comment in the Readme - I'd love to get sidekiq-unique-jobs working with ActiveJob. Mind you, it's not that I wouldn't like to switch to using `Sidekiq` directly, because I can assure you that I'd like to do that. But unfortunately, at the moment making this change would be rather significant. (ASIDE: Maybe you can suggest a simple way to do this? Or even provide a super lightweight tutorial on how to go about doing it?)

For now, I feel like I'm stuck looking for the proper way to implement sidekiq-unique-jobs with ActiveJob, but without much direction (thought the comments on Issue #244 were somewhat helpful).

The previous developers on the project simply added a copy&paste of the code from the README, and it seems like it's not working. Aka this code:
```

```
The intent was to prevent duplicate jobs (`:while_executing`) if they are of the same class. In other words, I don't care about the arguments being passed to `perform` -- instead, I just want to ensure two `ProductImportJob`s never run simultaneously in `sidekiq`. Here's our current code:
```
module XYZ
  class ProductImporterJob < ActiveJob::Base
    queue_as :default

    def perform(product_id, shop_id, commit: false)
      product_importer = XYZ::ProductImporterService.new

      ActiveRecord::Base.no_touching do
        product_importer.import_product(product_id, shop_id, commit: commit)
      end
    end
  end
end
```

Can you offer any advice? And either way, again, I'd humbly suggest a small comment in the README specifying something like:
`We are considering not supporting ActiveJob due to many questions. (See issues: #238 and #244) - Consider switching your project from using ActiveJob alongside Sidekiq to pure Sidekiq, because using them together takes a bunch of abstractions and such on ActiveJob to make it work right with any semi-complex requirements.`

**Comment by MFRWDesign** [comment]
Just thinking through might work based on the 'hack' in #76 by @jolim

Here's what I've got - but really not sure if this'll work. I think it at least illustrates my thoughts a bit more:
```
Sidekiq.default_worker_options = {
  unique: :until_and_while_executing,
  unique_args: lambda { |args|
    r = args.first.except('job_id')
    r[:jobclass] = r['class']
    [r]
  }
}
```
And I'm also wondering if I need this line in my sidekiq initializer:
```
SidekiqUniqueJobs.config.unique_args_enabled = true
```

**Comment by MFRWDesign** [comment]
@mhenrixon Just realising maybe I shouldn't have posted this on a closed issue. Can you reopen this? Or what do you think?

**Comment by adrianmann** [comment]
@MFRWDesign I apologies also fro commenting on a closed thread but they did you succeed on getting two jobs to run but not at the same time.

**Comment by mhenrixon** [comment]
@adrianmann @MFRWDesign I decided to stop trying to support ActiveJob. The default worker options will be removed for the next major release to really prevent people from using this gem with ActiveJob. There have been too much hassle with this.

**Comment by sharshenov** [comment]
@mhenrixon Do you mind if I add few lines do documentation and Wiki about alternative implementation exclusive for ActiveJob? [activejob-uniqueness](https://github.com/veeqo/activejob-uniqueness)
