### ISSUE TITLE
:until_executing not unlocking when starting to run

### ISSUE THREAD

**Issue by swarzech** [mhenrixon/sidekiq-unique-jobs#245]
I have a queue that has the unique set to until_executing with log_duplicate_payload set to true.  The queue is empty but when call preform_async for the worker I am getting the "payload is not unique" error.

sidekiq: 3.4.1
sidekiq-unique-jobs: 4.0.18
redis: 2.8.4

I know that I am a few versions behind but at the moment we are not going to update redis 3 yet.

Thanks.

**Comment by mhenrixon** [comment]
Unfortunately older versions were less than good enough. I've decided not to support versions older than 6 and rather focus all my efforts on making version 6 work really well.

I hope you don't mind and find it possible to upgrade redis so that you can use the new stuff (or create a PR for the branch `v4.x`).
