### ISSUE TITLE
Removed default lock from workers?

### ISSUE THREAD

**Issue by dbenjamin57** [mhenrixon/sidekiq-unique-jobs#323]
Hey, I just read the new documentation re the removal of the default lock from workers. 
This sounds risky and wrong.

I am referring to this piece of the documentation:
> In previous versions there was a default expiration of 30 minutes which didn't work for a lot of long running jobs. Since version 6 there will be no expiration of any jobs from the default configuration. Please don't use lock_expiration unless you really know what you are doing.

This means that if a job is ever deleted from the queues (for any reason) or a user manually deletes a job from the queue - the key will be locked FOREVER. How can this be the correct solution?  I've never seen a locking system that doesn't set a default lock timeout. 

If this is the case, I will have to manually add a lock expiration for every single job I have in my system... 

Can you explain your reasoning?

**Comment by mhenrixon** [comment]
Glad you asked @dbenjamin57. First of all my apologies for your situation. In all honesty, this was something I did not anticipate. I really did my best to make sure it was a painless upgrade. 

The default lock expiration was always set. This means that all jobs were locked from the second they are created until 30 minutes after creation. I had a ton of complaints because some people had extremely long running jobs (talking unpredictable hours). Unfortunately setting the expiration to nil explicitly in the worker made the default expiration kick in. 

I felt that any expiration should be explicit since every situation where expiration is used could for a long time lead to duplicate jobs being allowed.

A better way of dealing with this would be to only expire the job from when the server is done executing the job so that it would be more predictable. Then a global setting might make sense and I would consider having it. Until then I would rather people run into problems with locks not being expired than allowing duplicates. This gem is primarily about avoiding duplicate jobs and since v5 was really unreliable and duplicates happening too frequently I decided to take a step back and make absolutely sure it is reliable first and foremost. 

I have already started to play with expiring the locks upon completion rather than creation. Before I release that though I want to provide a way to validate the worker configuration and provide some feedback for settings that are perhaps not so compatible (like the conflict strategies and expiration in certain cases).

The `sidekiq_options` do a merge so adding a new line for that setting meanwhile might be an option. Can't guarantee exactly when I will be able to get to the lock expiration improvements. Looking at a pretty busy autumn with moving countries and getting everything set up.

Another suggestion to fix your problem would be creating an initializer that does the following:

```ruby
# config/initializers/
require 'sidekiq'
Dir['app/workers/**/*.rb'].each { |worker_file| require worker_file }

module Sidekiq::Worker
  def self.descendants
    ObjectSpace.each_object(Class).select { |klass| klass < self }
  end
end

Sidekiq::Worker.descendants.each do |worker_class|
  worker_class.sidekiq_options(lock_expiration: 30.minutes)
end
```

This code is highly untested and you probably have to fix a few typos and such. 

Does that help at all?

**Comment by erated** [comment]
Hey Mika, thanks for the detailed answer and good luck with the move! 

You wrote the following:

> A better way of dealing with this would be to only expire the job from when the server is done executing the job so that it would be more predictable.

I thought this is already what is happening when a job is completed (until_and_while_executing) ?

As I see it its very simple, unique jobs limits enqueue for a specific certain of default time which is highly likely to cover most cases and some people that have long running jobs (also us) can lock their enqueue for X amount of hours or so. In addition to this, we have also implemented a check before running long sensitive workers that they are "singeltons" (single running workers of a specific type).

**Comment by mhenrixon** [comment]
@dbenjamin57 @erated if you have any suggestions how to handle this change in lock expiration without causing people problems, I am all for just getting it done.

What I am afraid of an why I haven't done it yet is because people will all of a sudden expire their locks way later than they thought. How can I communicate this to the people who upgrade?

Upgrade note in the gem, readme, changelog? It isn't a breaking change so I hesitate to use v6.1 for this but maybe I should?

**Comment by erated** [comment]
It was already a breaking change in v6 as default lock was half an hour and now its indefinite...

**Comment by mhenrixon** [comment]
Fair point @erated I wish I had someone to pair with sometimes... I'll see about getting it done then. Can't make any promises on exactly when but it should be soon. 

Sorry about the trouble and thank you all for the input.

**Comment by erated** [comment]
no worries! Happy to help further. I'll try and get into the code a bit further this weekend and not just into the documentation.

**Comment by guillaumedenece** [comment]
Some of our jobs are also getting locked forever.
We are using AWS elastic beanstalk with a CI / CD process. What I noticed is that when we push new code and automatically deploy it, our job get stopped. Since the retry option is set to false, the job never is retried but the digest still is present, resulting in an endless dropping of this particular job when enqueued.

We of course use that configuration:
```
Sidekiq.configure_server do |config|
  config.death_handlers << lambda do |job, _ex|
    SidekiqUniqueJobs::Digests.del(digest: job['unique_digest']) if job['unique_digest']
  end
end
```
But it seems that this stopped job does not fall into the dead queue, so the digest never gets removed...

I guess the lock_expiration option could avoid that problem to happen but the best option would be to remove the digest at the time the job stops.

**Comment by mhenrixon** [comment]
@guillaumedenece see https://github.com/mperham/sidekiq/pull/3980#issuecomment-425140239 for more information. This has been changed in Sidekiq but you'd have to upgrade it. If you can't do that right now I suggest you change your `retry: false` to `retry: 0`.

**Comment by mhenrixon** [comment]
Also @ketiko ☝️

**Comment by guillaumedenece** [comment]
Thank you very much for your help @mhenrixon !

**Comment by mhenrixon** [comment]
I am closing this because expiration now only happens after the server is done processing the job.
