### ISSUE TITLE
Automatic unlock of jobs

### ISSUE THREAD

**Issue by Laykou** [mhenrixon/sidekiq-unique-jobs#362]
**Is your feature request related to a problem? Please describe.**
When sidekiq process is killed (SIGKILL) everything stays as-is in Redis. Sidekiq has mechanism of heartbeats to check if processor is still running or not. The same should apply for the unique jobs.

**Describe the solution you'd like**
I suggest some job that would periodically (e.g. every minute) check whether the *unique digest* lock is still valid = whether it is assigned to some running job. This would require to store also "JID" to each unique digest so that they can be paired together.

If the job is not running anymore it means the unique digest is stale and should be removed.

Otherwise it is blocking all future jobs until manual removal. I would like to prevent this manual removals by implementing this "auto-heal" feature.

**Comment by mhenrixon** [comment]
This has been discussed to death (pun intended). There is absolutely nothing the gem can or should do about this. If the job is back in redis it should still be considered unique because it will be retried.

- https://github.com/mperham/sidekiq/pull/3980#issuecomment-424825264
- https://github.com/mhenrixon/sidekiq-unique-jobs/issues/353
- https://github.com/mhenrixon/sidekiq-unique-jobs/issues/14
- https://github.com/mhenrixon/sidekiq-unique-jobs/issues/112
- https://github.com/mhenrixon/sidekiq-unique-jobs/pull/87

**Comment by mhenrixon** [comment]
If you feel like having a scheduled job to clear out jobs it is all on you :) I might create a better functionality for finding and clearing such jobs manually in the future but there needs to be manual intervention here. This is what Mike Perham does with the pro and enterprise versions of sidekiq.
