### ISSUE TITLE
Syntax error on using the v6.0.13

### ISSUE THREAD

**Issue by denisj** [mhenrixon/sidekiq-unique-jobs#410]
Hello everyone,

I'm currently using the v5.0.11 with Ruby 2.2.2 and Rails v4.0.13. And I'm trying to update to the v6.0.13. After the installation, when I'm opening a rails console, I get his :

sidekiq-unique-jobs-6.0.13/lib/sidekiq_unique_jobs/lock/base_lock.rb:125: syntax error, unexpected '.' (SyntaxError)  callback&.call

Is there a issue with Ruby 2.2.2?

Regards.

**Comment by mhenrixon** [comment]
Looks like I have been writing ruby 2.3 code but the readme says I should be supporting 2.2. In all honesty, I'm not sure I want to support ruby 2.2 at this point since it isn't officially supported anymore. It feels a little weird to not do it on a version that is supposed to have support though. 

Maybe I can be convinced in either direction... Any chance you could move over to ruby 2.3?

**Comment by denisj** [comment]
Thanks for your reply.

We have plan to move to Ruby 2.3.x, but son"t know when. So when the move is finished, I will update unique jobs ;)
