### ISSUE TITLE
Keys without TTL

### ISSUE THREAD

**Issue by collimarco** [mhenrixon/sidekiq-unique-jobs#417]
**Describe the bug**
There are many `uniquejobs:` keys that don't have a TTL. For example:

```
uniquejobs:ab35f7de5ca174ca59646ff77f99e07a:EXISTS
uniquejobs:fa33ca0af816809c3551eb7a506e27cd:EXISTS
uniquejobs:04655f4e7699ba934a5be59cef843038:GRABBED
...
```

If you delete all those keys, after a few minutes you have thousands of keys without TTL again.
Most keys are probably deleted in some other ways, because the number of keys without TTL doesn't increase too much over time. However, in order to **prevent memory leaks**, it would be useful to set a TTL for all the keys created, to **ensure** the eventual deletion. Setting a TTL would also make debugging memory leaks easier, because without that information, you have no idea if a key has been just created or it is long-lived trash.

**Expected behavior**
All the keys should be created with a TTL, possibly using `MULTI` to ensure that the TTL is set at the same time as the creation.

**Current behavior**
Many keys are created without a TTL. You can easily detect those keys running a task like this:

```
$redis.with do |conn|
  conn.scan_each(match: 'uniquejobs:*') do |key|
    puts key if conn.ttl(key) == -1
  end
end
```

**Worker class**

```ruby
class MyJob
  include Sidekiq::Worker
  sidekiq_options queue: :low, lock: :until_executing, lock_expiration: 600

  def perform(my_id)
    ...
  end
end
```

**Comment by mhenrixon** [comment]
This is already fixed in v7 (unreleased). I'll see about cutting a version `7.0.0.beta1` today

**Comment by mhenrixon** [comment]
`v7.0.0.beta2` released just now, I'll have a look tomorrow if I can make the TTL work for v6 as well.

**Comment by mhenrixon** [comment]
@collimarco the problem with your suggestion is that it might lead to duplicate jobs, which is precisely why v7 was created that takes a slightly different approach and automatically reaps orphaned locks (locks without a matching job).

When pushing a job it should be locked until the reaper detects that the lock is orphaned or the job completed. 

In case you delete the job, the lock should also be removed by the sidekiq process since the gem also hooks into `Sidekiq::Api` to do that for you.

Potentially, I might be persuaded to allow configuration of the lock expiration either from the lock or unlock. I'll have to think about that.

**Comment by mhenrixon** [comment]
I'm going to go ahead and close this one. I'm going to focus on v7 as much as possible. If you have any issues at all with version 7 open a new issue and I will tackle it immediately.
