### ISSUE TITLE
Reaper can't be registered again if sidekiq gets killed by SIGKILL

### ISSUE THREAD

**Issue by yaoyi** [mhenrixon/sidekiq-unique-jobs#490]
if sidekiq gets killed by SIGKILL, reaper can't clear its flag in redis, so next time, if we start sidekiq again, reaper can't get registered, therefore,  the timer task will not start either, the reaper task will never run in this case unless you clear the flag manually

**Comment by mhenrixon** [comment]
Need a reaper reaper :) I’ll tackle this in the next day or two.

**Comment by yaoyi** [comment]
hi @mhenrixon , i think maybe you don't need to provide a reaper reaper, which make things more sophisticated, you just provide an api, and we can call it from other cron job, for now, my workaround is to run the `SidekiqUniqueJobs::Orphans::Reaper.new(redis_conn).execute_lua_reaper` with sidekiq-cron for every 30 minutes

**Comment by mhenrixon** [comment]
Great suggestion! Thanks for all the amazing bug reports. I will prioritize these tickets so that v7 can finally be released at some point!

**Comment by mhenrixon** [comment]
@yaoyi I decided to make it a little more sophisticated. Since version 7.0.0.beta19 the reaper will now refresh a timestamp instead. Then when you boot up again after a sig kill it is less likely that you will run into problems with registration. 

It still isn't perfect but baby steps in the right direction :)
