### ISSUE TITLE
concurrent-ruby has dropped support for TimerTask timeouts

### ISSUE THREAD

**Issue by ClearlyClaire** [mhenrixon/sidekiq-unique-jobs#697]
`concurrent-ruby` 1.1.10 has dropped support for `TimerTask` timeouts: https://github.com/ruby-concurrency/concurrent-ruby/pull/926

However, `TimerTask` timeouts are in use in `sidekiq-unique-jobs`.

This leads to sidekiq regularly outputting the following in the logs, but beyond that, I don't know what are the exact implications:
> TimerTask timeouts are now ignored as these were not able to be implemented correctly

**Comment by mhenrixon** [comment]
Thanks for the report @ClearlyClaire! 

I've seen the warnings in one of the projects I am working on. I have some concerns about this since I actually fixed the timeouts to not leak threads so maybe I force a downgrade of concurrent-ruby. 

I am afraid that the timeout won't be respected anymore which would really cause problems for people using this gem.
