### ISSUE TITLE
Scheduled jobs are not unlocked when deleted

### ISSUE THREAD

**Issue by frsantos** [mhenrixon/sidekiq-unique-jobs#97]
I think an extension is missing for `Sidekiq::SortedEntry` in sidekiq_unique_ext.rb file.

**Comment by mhenrixon** [comment]
Why? Sorted set inherits from `Job` and should be handled by that?

**Comment by frsantos** [comment]
Yes, but SortedEntry redefines delete

**Comment by mhenrixon** [comment]
It just calls parent.delete which is jobset and already taken care of.

**Comment by mhenrixon** [comment]
Have a failing test for it?

**Comment by frsantos** [comment]
`SortedEntry#delete` calls `@parent.delete(score, jid)`, which is https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L522, and that method does not call `Job#delete`

**Comment by frsantos** [comment]
No sorry, no test, I just stumbled on the problem.

**Comment by frsantos** [comment]
Sorry, no time for creating a proper test, but you can see it failing with this code:

```ruby
class UniqueWorker
  include Sidekiq::Worker
  sidekiq_options unique: true

  def perform
    puts "Performing unique job"
  end
end

UniqueWorker.perform_in(1.hour)
=> nil

Sidekiq.redis {|conn| conn.keys 'sidekiq_unique*' }
=> ["sidekiq_unique:274be02062ac878719e069e2b804e761"]

Sidekiq::ScheduledSet.new.each(&:delete)
=> nil

Sidekiq.redis {|conn| conn.keys 'sidekiq_unique*' } 
=> ["sidekiq_unique:274be02062ac878719e069e2b804e761"]
````

Las sentence should return no keys.

**Comment by pik** [comment]
@mhenrixon I can reproduce this. The notable part is that there are two types of `delete` defined in the sidekiq api one in job and the other in [JobSet](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L522) - the later being the one which gets called when delete on a scheduled object runs; Although even if we fix that -- the delete defined under UniqueExtension would not be a sufficient replacement for the JobSet delete since the later can delete items by score.
Since the delete returns no information about which job was actually deleted it looks like SidekiqUnique needs to redeclare the entire method to hook into it. I don't know if there are any better ideas?

I have opened a tangential issue: https://github.com/mperham/sidekiq/issues/2472

**Comment by frsantos** [comment]
I have now this hack in extensions to make scheduled jobs work. However, the scheduled polling has no way to hook other than redefining the whole method :disappointed: 

https://gist.github.com/frsantos/e7e765874eb396e1abb6
